name: SkyStarModify
version: '${project.version}'
main: org.skystarmodify.SkyStarModify
api-version: '1.21'
depend:
  - CommandAPI
  - Essentials
  - NBTAPI
  - DiscordSRV
  - PlaceholderAPI
  - TaiwanifyEveryItem