name: SkyStarModify
version: '0.2.3'
main: org.skystarmodify.SkyStarModify
api-version: '1.21'
depend:
  - CommandAPI
  - Essentials
  - NBTAPI
  - DiscordSRV
  - PlaceholderAPI
  - TaiwanifyEveryItem